# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFDI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('serie', models.CharField(max_length=1)),
                ('asignarFolio', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('formaPago', models.CharField(max_length=5)),
                ('noCertificado', models.CharField(max_length=100)),
                ('condicionesDePago', models.CharField(max_length=100)),
                ('subtotal', models.CharField(max_length=100)),
                ('moneda', models.CharField(max_length=10)),
                ('tipoCambio', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('tipoComprobante', models.CharField(max_length=5)),
                ('metodoPago', models.CharField(max_length=50)),
                ('lugarExpedicion', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('rfcEmisor', models.CharField(max_length=50)),
                ('nombreEmisor', models.CharField(max_length=200)),
                ('regimenFiscalEmisor', models.CharField(max_length=100)),
                ('rfcReceptor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('usoCFDI', models.CharField(max_length=100)),
                ('claveProdServ', models.CharField(max_length=20)),
                ('noIdentificacion', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('claveUnidad', models.CharField(max_length=50)),
                ('unidadKilogramos', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('valorUnitario', models.CharField(max_length=50)),
                ('importe', models.CharField(max_length=20)),
                ('descuento', models.CharField(max_length=50)),
            ],
        ),
    ]
